updated yml again

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,44 +1,44 @@
 name: Weather Pipeline CI/CD (JS)
 
 on:
-  push: 
+  push:
   schedule:
-    - cron: "0 */2 * * *" 
-  workflow_dispatch //lets you manually trigger the workflow from gitHub
+    - cron: "0 */2 * * *"
+  workflow_dispatch:
 
 permissions:
-  contents: write 
+  contents: write
 
 jobs:
-  tests_and_fetch:
-    runs-on: ubuntu-latest 
-    steps: 
+  test_and_fetch:
+    runs-on: ubuntu-latest
+    steps:
       - name: Checkout repo
         uses: actions/checkout@v4
       - name: Use node.JS
         uses: actions/setup-node@v4
         with:
-              node-version: "22"
+            node-version: "22"
       - name: Cache Node Modules
         uses: actions/cache@v3
-        with: 
+        with:
             path: ~/.npm
             key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
       - name: Install Dependencies
-        run: npm ci 
-      - name: Fetch latest Weather  
+        run: npm ci
+      - name: Fetch latest Weather
         env:
-          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY}}
+          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
           CITY: ${{ secrets.CITY }}
-        run: node fetchWeather.js 
-      - name: run tests 
+        run: node fetchWeather.js
+      - name: Run tests
         run: npm test
-      - name: Comit weather data if it changes 
-        run: 
+      - name: Commit weather data if it changes
+        run: |
           git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git config user.email "github-action[bot]@users.noreply.github.com"
           git add data/weather.json data/weather_log.csv || true
-          git commit -m "ci update weather data" || echo "no changes to commit"
-          git push || echo "push failed or no changes"
-      - name: Trigger Render Deploy 
+          git commit -m "ci: update weather data" || echo "no changes to commit"
+          git push || echo 'push failed or no changes'
+      - name: Trigger Render Deploy
         run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
